'on': workflow_call
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.3-jammy
    strategy:
      fail-fast: false
      matrix:
        project: ['Android', 'Desktop Chrome', 'Desktop Safari', 'iOS']
    env:
      PUBLIC_FIREBASE_API_KEY: 'AIzaSyD3cNY62dZpsRtZmsU5Qn6LOGLUCjH7REk'
      PUBLIC_FIREBASE_AUTH_DOMAIN: 'listenlater.cloud'
      PUBLIC_FIREBASE_PROJECT_ID: 'listen-later-cloud'
      PUBLIC_FIREBASE_STORAGE_BUCKET: 'listen-later-cloud.appspot.com'
      PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '888811211358'
      PUBLIC_FIREBASE_APP_ID: '1:888811211358:web:0e351469eaead560e602cf'
      PUBLIC_FIREBASE_USE_EMULATORS: 'true'
      PUBLIC_FIREBASE_APPCHECK_DEBUG_TOKEN: '${{ secrets.FIREBASE_APPCHECK_DEBUG_TOKEN }}'
      PUBLIC_RECAPTCHA_SITE_KEY: '6Lcaxv4mAAAAAAGnxGlw3i8IgCzIJHeCdM3p0Ymp'
      SPOTIFY_CLIENT_ID: 'd46d2b58a44947d093ecbe0289a5dfc3'
      SPOTIFY_CLIENT_SECRET: '${{ secrets.SPOTIFY_CLIENT_SECRET }}'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Run site lint
        run: npm run lint
      - name: Run site type check
        run: npm run check
      - name: Run site unit tests
        run: npm run test:unit
      - name: Build site
        run: npm run build
      - name: Run functions lint
        run: npm run lint --workspace ./functions
      - name: Build functions
        run: npm run build --workspace ./functions
      - name: Install Java for Firebase Emulators
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Firebase Tools
        run: npm i -g firebase-tools
      - name: Write functions .env
        run: |
          touch ./functions/.env
          echo SPOTIFY_CLIENT_ID="$SPOTIFY_CLIENT_ID" >> ./functions/.env
          echo SPOTIFY_CLIENT_SECRET="$SPOTIFY_CLIENT_SECRET" >> ./functions/.env
          cat ./functions/.env
      # GOTCHA: If the Firebase Emulators hang when starting up, it's likely that a value is missing from .env and Functions is trying to prompt for it!
      - name: Run Playwright tests against Firebase Emulators
        run: firebase emulators:exec "npm run test:integration -- --project='${{ matrix.project }}'"
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report/
          retention-days: 3
