name: Buid, Test, Deploy to Firebase Hosting and Verify on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_test:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
  build_and_deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    env:
      PUBLIC_FIREBASE_API_KEY: 'AIzaSyD3cNY62dZpsRtZmsU5Qn6LOGLUCjH7REk'
      PUBLIC_FIREBASE_AUTH_DOMAIN: 'listenlater.cloud'
      PUBLIC_FIREBASE_PROJECT_ID: 'listen-later-cloud'
      PUBLIC_FIREBASE_STORAGE_BUCKET: 'listen-later-cloud.appspot.com'
      PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '888811211358'
      PUBLIC_FIREBASE_APP_ID: '1:888811211358:web:0e351469eaead560e602cf'
      PUBLIC_FIREBASE_USE_EMULATORS: 'false'
      PUBLIC_FIREBASE_APPCHECK_DEBUG_TOKEN: ''
      PUBLIC_RECAPTCHA_SITE_KEY: '6Lcaxv4mAAAAAAGnxGlw3i8IgCzIJHeCdM3p0Ymp'
      SPOTIFY_CLIENT_ID: 'd46d2b58a44947d093ecbe0289a5dfc3'
      SPOTIFY_CLIENT_SECRET: '${{ secrets.SPOTIFY_CLIENT_SECRET }}'
    steps:
      - uses: actions/checkout@v3
      - name: Generate new version number
        id: generate_version_number
        run: 'npx ts-node --esm --skipProject --compilerOptions "{\"module\": \"esnext\"}" ./generateVersionNumber.ts ${{ github.workflow_ref }} ${{ github.run_number }} >> $GITHUB_OUTPUT'
      - name: Set version
        run: npm version "${{ steps.generate_version_number.outputs.NEW_VERSION_NUMBER }}" --no-git-tag-version
      - name: Install dependencies
        run: npm ci
      - name: Run site type check
        run: npm run check
      - name: Build site
        run: npm run build
      - name: Build functions
        run: npm run build --workspace ./functions
      - name: Write functions .env
        run: |
          touch ./functions/.env
          echo SPOTIFY_CLIENT_ID="$SPOTIFY_CLIENT_ID" >> ./functions/.env
          echo SPOTIFY_CLIENT_SECRET="$SPOTIFY_CLIENT_SECRET" >> ./functions/.env
          cat ./functions/.env
      - name: Deploy Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LISTEN_LATER_CLOUD }}'
          projectId: listen-later-cloud
          channelId: live
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LISTEN_LATER_CLOUD }}'
      - name: Deploy Functions
        run: npx firebase-tools deploy --only functions --force
  verify:
    needs: build_and_deploy
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.36.2-jammy
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright smoke tests
        run: npm run test:smoke
        env:
          FIREBASE_APPCHECK_DEBUG_TOKEN: '${{ secrets.FIREBASE_APPCHECK_DEBUG_TOKEN }}'
          MAILINATOR_API_TOKEN: '${{ secrets.MAILINATOR_API_TOKEN }}'
      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-smoke-test-report
          path: playwright-report/
          retention-days: 3
